# 🚁 Skylark Drones — Business Intelligence Agent
### Monday.com × NLP — Founder-Level Query Engine

This notebook connects to your Monday.com workspace, fetches live Work Orders and Deals data, cleans it,
and lets you query it using **natural language powered by a pure NLP pipeline** — no external AI APIs required.

**Sections:**
1. Setup & Dependencies
2. Configuration
3. Monday.com Data Fetcher
4. Data Cleaning & Normalisation
5. Exploratory Analysis
6. NLP BI Agent (Natural Language Queries)
7. Leadership Update Generator
8. Utilities

## 1. Setup & Dependencies

> Run this cell first. Install with: `pip install requests pandas python-dateutil`

In [1]:
# ── Imports ──────────────────────────────────────────────
import os
import re
import math
import json
import requests
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta
from dateutil import parser as dateparser
from collections import defaultdict, Counter
from IPython.display import display, Markdown, HTML
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 60)
pd.set_option('display.float_format', '{:,.0f}'.format)

print('✅ Imports OK')

✅ Imports OK

## 2. Configuration

Set your Monday.com API token below. **Never commit real tokens to version control.**
Use environment variables in production.

In [3]:
# ── API Key ──────────────────────────────────────────────
# Option A: set directly (demo only)
MONDAY_API_TOKEN = os.getenv('MONDAY_API_TOKEN', 'eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjYzMTAwNjMwMSwiYWFpIjoxMSwidWlkIjoxMDA4MTI5OTMsImlhZCI6IjIwMjYtMDMtMTBUMDU6NDU6NDIuMDQ5WiIsInBlciI6Im1lOndyaXRlIiwiYWN0aWQiOjM0MTUzNDI5LCJyZ24iOiJhcHNlMiJ9.8ajhaM2DOGF0I-9C9AWkSKv6QdLPqK5ABEmD3nmQa84')

# Option B: uncomment to enter interactively
# import getpass
# MONDAY_API_TOKEN = getpass.getpass('Monday.com API Token: ')

# Validate
assert MONDAY_API_TOKEN != 'YOUR_MONDAY_TOKEN_HERE', 'Set your Monday.com API token'
print('✅ Token configured')

✅ Token configured

## 3. Monday.com Data Fetcher

All queries go through the Monday.com GraphQL API. We discover boards dynamically — no hardcoded IDs.

In [4]:
# ── Monday.com GraphQL client ─────────────────────────────────────────

MONDAY_URL = 'https://api.monday.com/v2'

def monday_query(query: str, variables: dict = None) -> dict:
    """Execute a Monday.com GraphQL query."""
    headers = {
        'Content-Type': 'application/json',
        'Authorization': MONDAY_API_TOKEN,
        'API-Version': '2024-01',
    }
    payload = {'query': query}
    if variables:
        payload['variables'] = variables
    r = requests.post(MONDAY_URL, headers=headers, json=payload, timeout=30)
    r.raise_for_status()
    data = r.json()
    if 'errors' in data:
        raise RuntimeError(f"Monday GraphQL error: {data['errors']}")
    return data['data']


def list_boards() -> pd.DataFrame:
    """List all accessible boards."""
    data = monday_query('{ boards(limit: 50) { id name description items_count } }')
    return pd.DataFrame(data['boards'])


def get_board_items(board_id: str, limit: int = 500) -> list:
    """Fetch all items and their column values from a board."""
    q = '''
    query($id: [ID!], $limit: Int) {
      boards(ids: $id) {
        name
        columns { id title type }
        items_page(limit: $limit) {
          items {
            id name
            column_values { id text value column { title type } }
          }
        }
      }
    }
    '''
    data = monday_query(q, {'id': [board_id], 'limit': limit})
    board = data['boards'][0]
    return board['name'], board['columns'], board['items_page']['items']


def items_to_dataframe(items: list) -> pd.DataFrame:
    """Convert Monday.com items list to a flat DataFrame."""
    rows = []
    for item in items:
        row = {'_id': item['id'], '_name': item['name']}
        for cv in item['column_values']:
            col_title = cv['column']['title']
            row[col_title] = cv['text'] or None
        rows.append(row)
    return pd.DataFrame(rows)


print('✅ Monday.com client ready')

✅ Monday.com client ready

### 3.1 Discover & Load Boards

In [5]:
# ── Discover boards ────────────────────────────────────────────────────
boards_df = list_boards()
print(f'Found {len(boards_df)} boards in workspace:\n')
display(boards_df[['id', 'name', 'items_count']])

Found 3 boards in workspace:

           id                        name  items_count
0  5027110070                 Work Orders          182
1  5027109446  Subitems of Deals Pipeline            2
2  5027109439              Deals Pipeline          351

In [6]:
# ── Select your boards ────────────────────────────────────────────────────
def find_board_id(boards_df: pd.DataFrame, keyword: str) -> str:
    mask = boards_df['name'].str.lower().str.contains(keyword.lower())
    matches = boards_df[mask]
    if matches.empty:
        raise ValueError(f'No board found matching "{keyword}". Available: {boards_df["name"].tolist()}')
    return str(matches.iloc[0]['id']), matches.iloc[0]['name']

deals_id, deals_name = find_board_id(boards_df, 'deal')
wo_id, wo_name = find_board_id(boards_df, 'work order')

print(f'📋 Deals board   : [{deals_id}] {deals_name}')
print(f'📋 Work Orders   : [{wo_id}] {wo_name}')

📋 Deals board   : [5027109446] Subitems of Deals Pipeline
📋 Work Orders   : [5027110070] Work Orders

In [7]:
# ── Fetch both boards ────────────────────────────────────────────────────
print('Fetching Deals...')
_, deals_cols, deals_items = get_board_items(deals_id)
raw_deals = items_to_dataframe(deals_items)
print(f'  → {len(raw_deals)} rows, {len(raw_deals.columns)} columns')

print('Fetching Work Orders...')
_, wo_cols, wo_items = get_board_items(wo_id)
raw_wo = items_to_dataframe(wo_items)
print(f'  → {len(raw_wo)} rows, {len(raw_wo.columns)} columns')

print('\n✅ Data loaded')

Fetching Deals...
  → 3 rows, 5 columns
Fetching Work Orders...
  → 182 rows, 8 columns

✅ Data loaded

## 4. Data Cleaning & Normalisation

Real-world Monday.com data is messy. This section:
- Parses inconsistent date formats
- Strips currency symbols and commas from numeric fields
- Normalises status/sector text (case, whitespace)
- Reports data quality metrics

In [8]:
# ── Data quality reporter ───────────────────────────────────────────────────

def data_quality_report(df: pd.DataFrame, name: str):
    """Print a data quality summary for a DataFrame."""
    total = len(df)
    report = []
    for col in df.columns:
        if col.startswith('_'): continue
        null_pct = df[col].isna().mean() * 100
        unique = df[col].nunique()
        report.append({'Column': col, 'Null%': f'{null_pct:.0f}%', 'Unique values': unique})
    print(f'\n📊 Data Quality — {name} ({total} rows)')
    print('=' * 50)
    display(pd.DataFrame(report).sort_values('Null%', ascending=False))

data_quality_report(raw_deals, 'Deals')
data_quality_report(raw_wo, 'Work Orders')

📊 Data Quality — Deals (3 rows)
==================================================

   Column Null%  Unique values
0   Owner  100%              0
1  Status  100%              0
2    Date  100%              0

📊 Data Quality — Work Orders (182 rows)
==================================================

       Column Null%  Unique values
1      Status   99%              2
2        Date   97%              2
0      Person  100%              0
3       Value  100%              0
4  Start Date  100%              0
5    End Date  100%              0

In [9]:
# ── Normalisation utilities ──────────────────────────────────────────────────

DATE_FORMATS = [
    '%d/%m/%Y', '%m/%d/%Y', '%Y-%m-%d', '%d-%m-%Y',
    '%d %b %Y', '%d %B %Y', '%b %d, %Y', '%B %d, %Y',
    '%Y/%m/%d', '%d.%m.%Y',
]

def parse_date(val):
    """Try multiple date formats; return date or NaT."""
    if pd.isna(val) or str(val).strip() == '': return pd.NaT
    val = str(val).strip()
    for fmt in DATE_FORMATS:
        try: return datetime.strptime(val, fmt).date()
        except ValueError: pass
    try: return dateparser.parse(val, dayfirst=True).date()
    except Exception: return pd.NaT


def parse_currency(val):
    """Strip currency symbols and commas, return float or NaN."""
    if pd.isna(val): return float('nan')
    cleaned = re.sub(r'[^\d.]', '', str(val).replace(',', ''))
    try: return float(cleaned) if cleaned else float('nan')
    except ValueError: return float('nan')


def normalise_text(val):
    """Trim and title-case a text field."""
    if pd.isna(val): return None
    return ' '.join(str(val).split()).strip()


def normalise_status(val):
    """Normalise status labels to a consistent format."""
    if pd.isna(val): return None
    v = str(val).strip().lower()
    mapping = {
        'in progress': 'In Progress', 'in-progress': 'In Progress', 'wip': 'In Progress',
        'done': 'Completed', 'complete': 'Completed', 'completed': 'Completed', 'closed': 'Completed',
        'not started': 'Not Started', 'new': 'Not Started', 'open': 'Not Started',
        'stuck': 'Blocked', 'blocked': 'Blocked', 'on hold': 'On Hold',
        'won': 'Won', 'closed won': 'Won', 'close won': 'Won',
        'lost': 'Lost', 'closed lost': 'Lost',
        'qualified': 'Qualified', 'lead': 'Lead', 'prospect': 'Prospect',
        'proposal': 'Proposal', 'negotiation': 'Negotiation', 'negotiating': 'Negotiation',
    }
    return mapping.get(v, ' '.join(w.capitalize() for w in v.split()))


print('✅ Normalisation functions defined')

✅ Normalisation functions defined

In [10]:
# ── Detect and clean column types automatically ─────────────────────────────

def auto_clean(df: pd.DataFrame, board_type: str) -> pd.DataFrame:
    """
    Auto-detect column roles by name and clean accordingly.
    board_type: 'deals' or 'workorders'
    """
    df = df.copy()
    DATE_KEYWORDS     = ['date', 'deadline', 'due', 'close', 'start', 'end', 'created']
    CURRENCY_KEYWORDS = ['value', 'amount', 'revenue', 'price', 'budget', 'cost', 'worth', 'arr', 'mrr']
    STATUS_KEYWORDS   = ['status', 'stage', 'phase', 'state', 'priority']
    SECTOR_KEYWORDS   = ['sector', 'industry', 'vertical', 'type', 'category', 'segment']
    cleaned_cols = {'date': [], 'currency': [], 'status': [], 'sector': []}

    for col in df.columns:
        if col.startswith('_'): continue
        col_lower = col.lower()
        if any(k in col_lower for k in DATE_KEYWORDS):
            df[col] = df[col].apply(parse_date)
            df[col] = pd.to_datetime(df[col], errors='coerce')
            cleaned_cols['date'].append(col)
        elif any(k in col_lower for k in CURRENCY_KEYWORDS):
            df[col] = df[col].apply(parse_currency)
            cleaned_cols['currency'].append(col)
        elif any(k in col_lower for k in STATUS_KEYWORDS):
            df[col] = df[col].apply(normalise_status)
            cleaned_cols['status'].append(col)
        elif any(k in col_lower for k in SECTOR_KEYWORDS):
            df[col] = df[col].apply(normalise_text)
            cleaned_cols['sector'].append(col)
        else:
            df[col] = df[col].apply(normalise_text)

    df['_name'] = df['_name'].apply(normalise_text)
    print(f'Cleaned columns:')
    for k, v in cleaned_cols.items():
        if v: print(f'  {k:12s}: {v}')
    return df


print('Cleaning Deals...')
deals = auto_clean(raw_deals, 'deals')

print('\nCleaning Work Orders...')
wo = auto_clean(raw_wo, 'workorders')

print('\n✅ Cleaning complete')

Cleaning Deals...
Cleaned columns:
  date        : ['Date']
  status      : ['Status']

Cleaning Work Orders...
Cleaned columns:
  date        : ['Date', 'Start Date', 'End Date']
  currency    : ['Value']
  status      : ['Status']

✅ Cleaning complete

In [11]:
# ── Preview cleaned data ──────────────────────────────────────────────────
print('=== DEALS (first 5 rows) ===')
display(deals.head())
print('\n=== WORK ORDERS (first 5 rows) ===')
display(wo.head())

=== DEALS (first 5 rows) ===

          _id             _name Owner Status Date
0  2622350047           Subitem  None   None  NaT
1  2622348438  Initial Contract  None   None  NaT
2  2622353978         Extension  None   None  NaT

=== WORK ORDERS (first 5 rows) ===

          _id         _name Person Status Date  Value Start Date End Date
0  2622444049      Serial #   None   None  NaT    NaN        NaT      NaT
1  2622407838  SDPLDEAL-075   None   None  NaT    NaN        NaT      NaT
2  2622453799  SDPLDEAL-101   None   None  NaT    NaN        NaT      NaT
3  2622453871  SDPLDEAL-002   None   None  NaT    NaN        NaT      NaT
4  2622407943  SDPLDEAL-003   None   None  NaT    NaN        NaT      NaT

## 5. Exploratory Analysis

Quick-look summaries before natural language querying.

In [12]:
# ── Helper: find best column for a concept ─────────────────────────────────

def find_col(df, keywords):
    """Find the first column whose name contains any keyword (case-insensitive)."""
    for kw in keywords:
        for col in df.columns:
            if kw.lower() in col.lower():
                return col
    return None


# ── Detect key columns ────────────────────────────────────────────────────
val_col       = find_col(deals, ['value', 'amount', 'revenue', 'arr', 'deal size'])
status_col    = find_col(deals, ['stage', 'status', 'phase'])
sector_col    = find_col(deals, ['sector', 'industry', 'vertical', 'segment'])
wo_val_col    = find_col(wo, ['value', 'amount', 'budget', 'revenue', 'cost', 'price'])
wo_status_col = find_col(wo, ['status', 'stage', 'state'])
wo_sector_col = find_col(wo, ['sector', 'industry', 'client', 'category', 'type'])

print(f'Deals   → value: {val_col}, status: {status_col}, sector: {sector_col}')
print(f'WO      → value: {wo_val_col}, status: {wo_status_col}, sector: {wo_sector_col}')

if val_col and status_col:
    summary = deals.groupby(status_col)[val_col].agg(['count', 'sum', 'mean'])
    summary.columns = ['Count', 'Total Value', 'Avg Value']
    summary = summary.sort_values('Total Value', ascending=False)
    print('\n📊 Deals by Stage:')
    display(summary)

Deals   → value: None, status: Status, sector: None
WO      → value: Value, status: Status, sector: None

In [13]:
# ── Work Orders summary ───────────────────────────────────────────────────
if wo_status_col:
    if wo_val_col:
        wo_summary = wo.groupby(wo_status_col)[wo_val_col].agg(['count', 'sum'])
        wo_summary.columns = ['Count', 'Total Value']
    else:
        wo_summary = wo.groupby(wo_status_col)['_id'].count().rename('Count').to_frame()
    wo_summary = wo_summary.sort_values('Count', ascending=False)
    print('📊 Work Orders by Status:')
    display(wo_summary)

📊 Work Orders by Status:

               Count  Total Value
Status
Completed          0            0
Working On It      0            0

In [14]:
# ── Sector breakdown (cross-board) ─────────────────────────────────────────
dfs_with_sector = []
if sector_col and val_col:
    d = deals[[sector_col, val_col]].copy()
    d.columns = ['Sector', 'Value']
    d['Source'] = 'Deals'
    dfs_with_sector.append(d)
if wo_sector_col and wo_val_col:
    w = wo[[wo_sector_col, wo_val_col]].copy()
    w.columns = ['Sector', 'Value']
    w['Source'] = 'Work Orders'
    dfs_with_sector.append(w)
if dfs_with_sector:
    combined = pd.concat(dfs_with_sector, ignore_index=True)
    combined['Sector'] = combined['Sector'].apply(normalise_text)
    sector_summary = combined.groupby(['Sector', 'Source'])['Value'].sum().unstack(fill_value=0)
    sector_summary['Total'] = sector_summary.sum(axis=1)
    sector_summary = sector_summary.sort_values('Total', ascending=False).head(15)
    print('📊 Top Sectors (cross-board):')
    display(sector_summary)
else:
    print('No sector+value columns found for cross-board analysis.')

No sector+value columns found for cross-board analysis.

## 6. NLP BI Agent (Natural Language Queries)

This agent processes your questions in plain English using a **pure NLP pipeline** — no external AI API needed.

### How it works:
1. **Tokenisation & preprocessing** — lowercases, removes punctuation, filters stopwords
2. **Intent classification** — TF-IDF style keyword scoring across 7 intent categories
3. **Named entity extraction** — regex patterns for time periods, sectors, deal stages, metrics
4. **Query execution** — dispatches to pandas-based computation functions on live DataFrames
5. **Response generation** — structured Markdown templates filled with real computed values
6. **Context tracking** — remembers last query intent for follow-up questions

In [15]:
# ── NLP Core: Tokeniser & Preprocessor ───────────────────────────────────

STOPWORDS = {
    'a','an','the','is','are','was','were','be','been','being',
    'have','has','had','do','does','did','will','would','could',
    'should','may','might','shall','can','need','dare','ought',
    'i','me','my','we','us','our','you','your','it','its',
    'this','that','these','those','what','which','who','whom',
    'how','when','where','why','all','any','each','few','more',
    'most','some','such','no','not','only','own','same','so',
    'than','too','very','just','but','if','or','and','of','to',
    'in','for','on','with','at','by','from','up','about','into',
    'through','during','before','after','above','below','between',
    'give','me','show','tell','get','list','find','what','whats',
    'their','let','like','looking','overall','across','both',
}

def tokenise(text: str) -> list:
    """Lowercase, remove punctuation, split into tokens, filter stopwords."""
    text = text.lower()
    text = re.sub(r'[^\w\s]', ' ', text)
    tokens = text.split()
    return [t for t in tokens if t not in STOPWORDS and len(t) > 1]


def bigrams(tokens: list) -> list:
    """Generate bigrams from token list."""
    return [f'{tokens[i]}_{tokens[i+1]}' for i in range(len(tokens)-1)]


print('✅ NLP tokeniser ready')

✅ NLP tokeniser ready

In [16]:
# ── Intent Classifier ────────────────────────────────────────────────────
#
# Each intent has signal tokens + bigrams with weights.
# Token match = 1.0 pt, Bigram match = 2.0 pt (more specific), scaled by intent weight.

INTENT_VOCAB = {
    'pipeline_overview': {
        'tokens':  ['pipeline', 'funnel', 'deals', 'stages', 'stage', 'breakdown',
                    'overview', 'summary', 'health', 'status', 'prospects'],
        'bigrams': ['pipeline_health', 'sales_pipeline', 'deal_stage', 'stage_breakdown'],
        'weight':  1.0,
    },
    'revenue': {
        'tokens':  ['revenue', 'value', 'amount', 'income', 'sales', 'booking',
                    'arr', 'mrr', 'contracted', 'money', 'worth', 'total'],
        'bigrams': ['total_value', 'deal_value', 'booking_value', 'total_revenue'],
        'weight':  1.0,
    },
    'sector_analysis': {
        'tokens':  ['sector', 'industry', 'vertical', 'energy', 'healthcare',
                    'technology', 'manufacturing', 'retail', 'finance', 'segment'],
        'bigrams': ['sector_performance', 'by_sector', 'sector_revenue', 'industry_breakdown'],
        'weight':  1.2,
    },
    'work_orders': {
        'tokens':  ['work', 'order', 'orders', 'project', 'projects', 'operational',
                    'completion', 'complete', 'completed', 'active', 'execution',
                    'overdue', 'blocked', 'delay', 'delayed'],
        'bigrams': ['work_order', 'work_orders', 'completion_rate', 'project_status'],
        'weight':  1.0,
    },
    'at_risk': {
        'tokens':  ['risk', 'stall', 'stalling', 'stuck', 'overdue', 'late', 'delayed',
                    'attention', 'warn', 'warning', 'flag', 'problem', 'issue', 'concern'],
        'bigrams': ['at_risk', 'risk_deals', 'stalled_deals', 'overdue_deals'],
        'weight':  1.3,
    },
    'forecast': {
        'tokens':  ['forecast', 'prediction', 'projection', 'outlook', 'expect',
                    'future', 'next', 'upcoming', 'trend', 'trajectory'],
        'bigrams': ['revenue_forecast', 'pipeline_forecast', 'next_quarter'],
        'weight':  1.2,
    },
    'leadership_update': {
        'tokens':  ['leadership', 'update', 'briefing', 'report', 'weekly',
                    'board', 'executive', 'summary', 'kpi', 'metrics', 'dashboard'],
        'bigrams': ['leadership_update', 'weekly_update', 'executive_summary', 'kpi_dashboard'],
        'weight':  1.2,
    },
}


def classify_intent(query: str) -> tuple:
    """
    Score query tokens against intent vocabulary.
    Returns (best_intent, score_dict, all_tokens).
    """
    tokens    = tokenise(query)
    bigs      = bigrams(tokens)
    token_set = set(tokens)
    big_set   = set(bigs)

    scores = {}
    for intent, cfg in INTENT_VOCAB.items():
        score = 0.0
        for t in cfg['tokens']:
            if t in token_set: score += 1.0
        for b in cfg['bigrams']:
            if b in big_set: score += 2.0
        scores[intent] = score * cfg['weight']

    best = max(scores, key=scores.get) if max(scores.values()) > 0 else 'general'
    return best, scores, tokens


print('✅ Intent classifier ready')

# Quick test
intent, _, _ = classify_intent("How's our sales pipeline looking overall?")
print(f'   Test: "pipeline" → intent={intent}')

✅ Intent classifier ready
   Test: "pipeline" → intent=pipeline_overview

In [17]:
# ── Named Entity Extractor ────────────────────────────────────────────────

SECTOR_ENTITIES = [
    'energy', 'oil', 'gas', 'power', 'utilities',
    'healthcare', 'pharma', 'medical', 'hospital',
    'technology', 'tech', 'software', 'it',
    'manufacturing', 'industrial', 'factory',
    'retail', 'ecommerce', 'consumer',
    'finance', 'banking', 'insurance', 'fintech',
    'real estate', 'construction', 'infrastructure',
    'agriculture', 'agri', 'food',
    'telecom', 'logistics', 'transport',
    'defence', 'defense', 'government',
]

STAGE_ENTITIES = [
    'lead', 'prospect', 'qualified', 'proposal',
    'negotiation', 'negotiating', 'won', 'lost',
    'closed', 'in progress', 'completed', 'blocked', 'on hold'
]


def extract_time_period(query: str) -> dict:
    """Extract time-related entities from query."""
    q = query.lower()
    result = {}

    qm = re.search(r'\bq([1-4])\b', q)
    if qm: result['quarter'] = f'Q{qm.group(1)}'

    if re.search(r'\b(this|current)\s+quarter\b', q):
        now = datetime.now()
        result['quarter'] = f'Q{(now.month-1)//3+1}'
        result['year']    = now.year
        result['relative'] = 'current'
    elif re.search(r'\b(last|previous|prior)\s+quarter\b', q):
        now   = datetime.now()
        prev_q = ((now.month-1)//3)
        result['quarter']  = f'Q{prev_q if prev_q > 0 else 4}'
        result['year']     = now.year if prev_q > 0 else now.year - 1
        result['relative'] = 'previous'

    months = ['january','february','march','april','may','june',
               'july','august','september','october','november','december',
               'jan','feb','mar','apr','jun','jul','aug','sep','oct','nov','dec']
    for m in months:
        if re.search(r'\b' + m + r'\b', q):
            result['month'] = m.capitalize()
            break

    ym = re.search(r'\b(20\d{2})\b', query)
    if ym: result['year'] = int(ym.group(1))

    if re.search(r'\b(this|current)\s+(month|year)\b', q):
        result['relative'] = 'current'
    elif re.search(r'\b(ytd|year.to.date)\b', q):
        result['relative'] = 'ytd'

    if re.search(r'\b(vs|versus|compared|comparison)\b', q):
        result['is_comparison'] = True

    return result


def extract_sector(query: str):
    """Return sector name if found in query, else None."""
    q = query.lower()
    for s in SECTOR_ENTITIES:
        if re.search(r'\b' + re.escape(s) + r'\b', q):
            return s.title()
    return None


def extract_stage(query: str):
    """Return deal stage if explicitly mentioned."""
    q = query.lower()
    for s in STAGE_ENTITIES:
        if re.search(r'\b' + re.escape(s) + r'\b', q):
            return s.title()
    return None


def extract_top_n(query: str):
    """Extract 'top N' from query."""
    m = re.search(r'\b(top|bottom)\s+(\d+)\b', query.lower())
    if m: return int(m.group(2))
    return None


def extract_entities(query: str) -> dict:
    """Run all entity extractors and return combined dict."""
    return {
        'time':   extract_time_period(query),
        'sector': extract_sector(query),
        'stage':  extract_stage(query),
        'top_n':  extract_top_n(query),
    }


print('✅ Named entity extractor ready')
e = extract_entities('Show me energy sector deals for Q2 2024')
print(f'   Test → {e}')

✅ Named entity extractor ready
   Test → {'time': {'quarter': 'Q2', 'year': 2024}, 'sector': 'Energy', 'stage': None, 'top_n': None}

In [18]:
# ── DataFrame Query Engine ────────────────────────────────────────────────

def _filter_by_time(df, time_ents, date_col=None):
    """Filter DataFrame by extracted time entities."""
    if not time_ents or not date_col or date_col not in df.columns:
        return df
    now  = datetime.now()
    mask = pd.Series([True] * len(df), index=df.index)
    dc   = pd.to_datetime(df[date_col], errors='coerce')
    if 'year'    in time_ents: mask &= (dc.dt.year    == time_ents['year'])
    if 'quarter' in time_ents:
        qnum = int(time_ents['quarter'][1])
        mask &= (dc.dt.quarter == qnum)
    if 'month'   in time_ents:
        mmap = {'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,
                'Jul':7,'Aug':8,'Sep':9,'Oct':10,'Nov':11,'Dec':12,
                'January':1,'February':2,'March':3,'April':4,'June':6,
                'July':7,'August':8,'September':9,'October':10,'November':11,'December':12}
        mnum = mmap.get(time_ents['month'])
        if mnum: mask &= (dc.dt.month == mnum)
    if time_ents.get('relative') == 'ytd':
        mask &= (dc.dt.year == now.year) & (dc <= pd.Timestamp(now))
    return df[mask]


def _filter_by_sector(df, sector, scol=None):
    """Filter DataFrame by sector string."""
    if not sector or not scol or scol not in df.columns: return df
    mask = df[scol].str.lower().str.contains(sector.lower(), na=False)
    res  = df[mask]
    return res if len(res) > 0 else df


def _safe_sum(s):  return float(s.dropna().sum())
def _safe_mean(s): return float(s.dropna().mean()) if len(s.dropna()) > 0 else 0.0

def _fmt(val):
    if val >= 1_000_000: return f'\u20b9{val/1_000_000:.2f}M'
    elif val >= 1_000:   return f'\u20b9{val/1_000:.1f}K'
    return f'\u20b9{val:,.0f}'


def query_pipeline_overview(entities):
    df   = deals.copy()
    dcol = find_col(df, ['date','created','close','due'])
    if entities['time']:   df = _filter_by_time(df, entities['time'], dcol)
    if entities['sector']: df = _filter_by_sector(df, entities['sector'], sector_col)

    total     = len(df)
    total_val = _safe_sum(df[val_col]) if val_col else 0
    stage_breakdown = {}
    if status_col and val_col:
        for stage, grp in df.groupby(status_col):
            stage_breakdown[stage] = {'count': len(grp), 'value': _safe_sum(grp[val_col])}
    elif status_col:
        for stage, grp in df.groupby(status_col):
            stage_breakdown[stage] = {'count': len(grp), 'value': 0}

    won_stages  = [s for s in stage_breakdown if 'won' in s.lower()]
    lost_stages = [s for s in stage_breakdown if 'lost' in s.lower()]
    won_count   = sum(stage_breakdown[s]['count'] for s in won_stages)
    lost_count  = sum(stage_breakdown[s]['count'] for s in lost_stages)
    denom       = total - lost_count
    win_rate    = (won_count / denom * 100) if denom > 0 else 0

    return {
        'type': 'pipeline_overview', 'total_deals': total, 'total_value': total_val,
        'stage_breakdown': stage_breakdown, 'won_count': won_count, 'lost_count': lost_count,
        'win_rate': win_rate, 'filter_sector': entities['sector'], 'filter_time': entities['time'],
        'data_quality': f"{int(df[val_col].isna().sum())} deals missing value" if val_col else 'No value col',
    }


def query_revenue(entities):
    df   = deals.copy()
    dcol = find_col(df, ['date','created','close'])
    if entities['time']:   df = _filter_by_time(df, entities['time'], dcol)
    if entities['sector']: df = _filter_by_sector(df, entities['sector'], sector_col)
    if entities.get('stage') and status_col:
        mask = df[status_col].str.lower().str.contains(entities['stage'].lower(), na=False)
        if mask.sum() > 0: df = df[mask]

    total_val = _safe_sum(df[val_col]) if val_col else 0
    avg_val   = _safe_mean(df[val_col]) if val_col else 0
    max_deal  = None
    if val_col and len(df) > 0 and not df[val_col].isna().all():
        idx = df[val_col].idxmax()
        max_deal = {'name': df.loc[idx, '_name'], 'value': df.loc[idx, val_col]}
    by_sector = {}
    if sector_col and val_col:
        by_sector = df.groupby(sector_col)[val_col].sum().sort_values(ascending=False).head(8).to_dict()
    return {
        'type': 'revenue', 'count': len(df), 'total_value': total_val, 'avg_value': avg_val,
        'largest_deal': max_deal, 'by_sector': by_sector,
        'filter_sector': entities['sector'], 'filter_stage': entities.get('stage'),
        'filter_time': entities['time'],
        'missing_value': int(df[val_col].isna().sum()) if val_col else 'N/A',
    }


def query_sector_analysis(entities):
    result = {'type': 'sector_analysis', 'deals': {}, 'work_orders': {}}
    if sector_col and val_col:
        s = deals.groupby(sector_col)[val_col].agg(['count','sum','mean'])
        s.columns = ['deals','total_value','avg_value']
        result['deals'] = s.sort_values('total_value', ascending=False).head(10).to_dict('index')
    if wo_sector_col:
        agg_col = wo_val_col if wo_val_col else '_id'
        if wo_val_col:
            w = wo.groupby(wo_sector_col)[wo_val_col].agg(['count','sum'])
            w.columns = ['orders','total_value']
        else:
            w = wo.groupby(wo_sector_col)['_id'].count().rename('orders').to_frame()
            w['total_value'] = 0
        result['work_orders'] = w.sort_values('orders', ascending=False).head(10).to_dict('index')
    return result


def query_work_orders(entities):
    df   = wo.copy()
    dcol = find_col(df, ['date','start','due','deadline','end'])
    if entities['time']:   df = _filter_by_time(df, entities['time'], dcol)
    if entities['sector']: df = _filter_by_sector(df, entities['sector'], wo_sector_col)

    total        = len(df)
    status_counts = df[wo_status_col].value_counts().to_dict() if wo_status_col else {}
    completed = sum(v for k,v in status_counts.items() if any(x in str(k).lower() for x in ['complet','done','won']))
    blocked   = sum(v for k,v in status_counts.items() if any(x in str(k).lower() for x in ['block','stuck']))
    in_prog   = sum(v for k,v in status_counts.items() if any(x in str(k).lower() for x in ['progress','active']))
    comp_rate = (completed / total * 100) if total > 0 else 0

    overdue = 0
    if dcol and dcol in df.columns:
        now_ts = pd.Timestamp(datetime.now())
        dc_ts  = pd.to_datetime(df[dcol], errors='coerce')
        if wo_status_col:
            not_done = ~df[wo_status_col].str.lower().str.contains('complet|done|won', na=False)
            overdue = int(((dc_ts < now_ts) & not_done & dc_ts.notna()).sum())
        else:
            overdue = int(((dc_ts < now_ts) & dc_ts.notna()).sum())

    return {
        'type': 'work_orders', 'total': total, 'completed': completed,
        'in_progress': in_prog, 'blocked': blocked, 'overdue': overdue,
        'completion_rate': comp_rate,
        'total_value': _safe_sum(df[wo_val_col]) if wo_val_col else 0,
        'status_breakdown': status_counts,
        'filter_sector': entities['sector'], 'filter_time': entities['time'],
    }


def query_at_risk(entities):
    df       = deals.copy()
    now_ts   = pd.Timestamp(datetime.now())
    dcol     = find_col(df, ['close','due','deadline','date'])
    at_risk  = []

    for _, row in df.iterrows():
        reasons = []
        if dcol and pd.notna(row.get(dcol)):
            try:
                close_dt = pd.to_datetime(row[dcol])
                if close_dt < now_ts:
                    reasons.append(f'Close date overdue by {(now_ts - close_dt).days}d')
            except: pass
        if status_col and str(row.get(status_col,'')).lower() in ['blocked','on hold','stuck']:
            reasons.append(f'Status: {row[status_col]}')
        if reasons:
            at_risk.append({'name': row['_name'], 'value': row.get(val_col), 'stage': row.get(status_col,'Unknown'), 'reasons': reasons})

    at_risk.sort(key=lambda x: float(x['value'] or 0) if x['value'] and not math.isnan(float(x['value'] or 0)) else 0, reverse=True)
    total_risk_val = sum(float(x['value']) for x in at_risk if x['value'] and not math.isnan(float(x['value'] or 0)))

    return {'type': 'at_risk', 'count': len(at_risk), 'items': at_risk[:10], 'total_at_risk_value': total_risk_val}


def query_forecast(entities):
    STAGE_PROB = {
        'lead':0.10,'prospect':0.20,'qualified':0.35,'proposal':0.50,
        'negotiation':0.75,'negotiating':0.75,'won':1.0,'closed won':1.0,'lost':0.0,'closed lost':0.0,
    }
    df             = deals.copy()
    weighted_total = 0.0
    by_stage       = {}

    if status_col and val_col:
        for _, row in df.iterrows():
            stage = str(row.get(status_col,'')).lower()
            try:   value = float(row.get(val_col,0) or 0)
            except: value = 0.0
            prob = STAGE_PROB.get(stage, 0.30)
            wv   = value * prob
            weighted_total += wv
            sd = row.get(status_col,'Unknown')
            if sd not in by_stage:
                by_stage[sd] = {'count':0,'raw_value':0,'weighted_value':0,'probability':prob}
            by_stage[sd]['count']          += 1
            by_stage[sd]['raw_value']      += value
            by_stage[sd]['weighted_value'] += wv

    return {
        'type': 'forecast', 'weighted_forecast': weighted_total,
        'total_pipeline': _safe_sum(df[val_col]) if val_col else 0,
        'by_stage': by_stage,
        'note': 'Probability weights: Lead 10%, Prospect 20%, Qualified 35%, Proposal 50%, Negotiation 75%, Won 100%',
    }


def query_general(entities, tokens):
    return {
        'type': 'general', 'deals_count': len(deals), 'wo_count': len(wo),
        'deals_value': _safe_sum(deals[val_col]) if val_col else 0,
        'wo_value': _safe_sum(wo[wo_val_col]) if wo_val_col else 0,
    }


QUERY_DISPATCH = {
    'pipeline_overview': query_pipeline_overview,
    'revenue':           query_revenue,
    'sector_analysis':   query_sector_analysis,
    'work_orders':       query_work_orders,
    'at_risk':           query_at_risk,
    'forecast':          query_forecast,
}


print('✅ Query engine ready')

✅ Query engine ready

In [19]:
# ── Response Generator ────────────────────────────────────────────────────
# Turns structured result dicts into human-readable Markdown.

def _time_label(te):
    if not te: return 'all time'
    parts = []
    if 'quarter'  in te: parts.append(te['quarter'])
    if 'month'    in te: parts.append(te['month'])
    if 'year'     in te: parts.append(str(te['year']))
    if 'relative' in te: parts.append(te['relative'].replace('_',' '))
    return ', '.join(parts) if parts else 'all time'


def render_pipeline_overview(r):
    t   = _time_label(r['filter_time'])
    sec = f" — {r['filter_sector']} sector" if r['filter_sector'] else ''
    lines = [f"## \U0001f4ca Pipeline Overview ({t}{sec})\n"]
    lines.append(f"**Total Deals:** {r['total_deals']}  |  **Pipeline Value:** {_fmt(r['total_value'])}  |  **Win Rate:** {r['win_rate']:.1f}%\n")
    if r['stage_breakdown']:
        lines += ['\n### Stage Breakdown', '| Stage | Count | Value |', '|-------|-------|-------|']
        for stage, info in sorted(r['stage_breakdown'].items(), key=lambda x: x[1]['value'], reverse=True):
            lines.append(f"| {stage} | {info['count']} | {_fmt(info['value'])} |")
    lines.append('\n### \U0001f4a1 Insights')
    if r['won_count'] > 0:   lines.append(f"- ✅ **{r['won_count']} deals won**")
    if r['win_rate'] < 20:   lines.append(f"- ⚠️ Win rate at **{r['win_rate']:.1f}%** — review qualification criteria")
    elif r['win_rate'] > 50: lines.append(f"- \U0001f3af Strong win rate of **{r['win_rate']:.1f}%**")
    if r.get('data_quality'): lines.append(f"\n> \U0001f4dd _{r['data_quality']}_")
    return '\n'.join(lines)


def render_revenue(r):
    t   = _time_label(r['filter_time'])
    sec = f" — {r['filter_sector']} sector" if r['filter_sector'] else ''
    stg = f" — {r['filter_stage']} stage" if r.get('filter_stage') else ''
    lines = [f"## \U0001f4b0 Revenue Analysis ({t}{sec}{stg})\n"]
    lines += ['| Metric | Value |', '|--------|-------|']
    lines.append(f"| Deals analysed | {r['count']} |")
    lines.append(f"| Total value | **{_fmt(r['total_value'])}** |")
    lines.append(f"| Average deal size | {_fmt(r['avg_value'])} |")
    if r['largest_deal']:
        lines.append(f"| Largest deal | {r['largest_deal']['name']} ({_fmt(r['largest_deal']['value'])}) |")
    if r['by_sector']:
        lines += ['\n### Revenue by Sector', '| Sector | Value |', '|--------|-------|']
        for sn, sv in list(r['by_sector'].items())[:8]:
            lines.append(f"| {sn} | {_fmt(sv)} |")
    if isinstance(r['missing_value'], int) and r['missing_value'] > 0:
        lines.append(f"\n> \U0001f4dd _{r['missing_value']} deals missing value data — totals may be understated._")
    return '\n'.join(lines)


def render_sector_analysis(r):
    lines = ['## \U0001f3ed Sector Performance (Cross-Board)\n']
    if r['deals']:
        lines += ['### Deals by Sector', '| Sector | Deals | Total Value | Avg Value |', '|--------|-------|-------------|-----------|']
        for sn, info in r['deals'].items():
            lines.append(f"| {sn} | {int(info['deals'])} | {_fmt(info['total_value'])} | {_fmt(info['avg_value'])} |")
    if r['work_orders']:
        lines += ['\n### Work Orders by Sector', '| Sector | Orders | Total Value |', '|--------|--------|-------------|']
        for sn, info in r['work_orders'].items():
            lines.append(f"| {sn} | {int(info['orders'])} | {_fmt(info.get('total_value',0))} |")
    return '\n'.join(lines)


def render_work_orders(r):
    t   = _time_label(r['filter_time'])
    sec = f" — {r['filter_sector']} sector" if r['filter_sector'] else ''
    lines = [f"## ⚙️ Work Orders Report ({t}{sec})\n"]
    lines += ['| Metric | Value |', '|--------|-------|']
    lines.append(f"| Total Orders | **{r['total']}** |")
    lines.append(f"| Completed | ✅ {r['completed']} ({r['completion_rate']:.1f}%) |")
    lines.append(f"| In Progress | \U0001f504 {r['in_progress']} |")
    lines.append(f"| Blocked | \U0001f6ab {r['blocked']} |")
    lines.append(f"| Overdue | ⏰ {r['overdue']} |")
    if r['total_value'] > 0: lines.append(f"| Total Value | {_fmt(r['total_value'])} |")
    lines.append('\n### \U0001f4a1 Insights')
    if r['completion_rate'] >= 75:   lines.append(f"- \U0001f3af Strong completion rate of **{r['completion_rate']:.0f}%**")
    elif r['completion_rate'] < 40:  lines.append(f"- ⚠️ Low completion rate (**{r['completion_rate']:.0f}%**) — consider resource reallocation")
    if r['blocked'] > 0: lines.append(f"- \U0001f6a8 **{r['blocked']} blocked orders** — needs immediate attention")
    if r['overdue']  > 0: lines.append(f"- ⏰ **{r['overdue']} overdue orders** — review timelines")
    if r['status_breakdown']:
        lines += ['\n### Status Breakdown', '| Status | Count |', '|--------|-------|']
        for st, cnt in sorted(r['status_breakdown'].items(), key=lambda x: x[1], reverse=True):
            lines.append(f"| {st} | {cnt} |")
    return '\n'.join(lines)


def render_at_risk(r):
    lines = [f"## ⚠️ At-Risk Deals ({r['count']} flagged)\n"]
    if r['total_at_risk_value'] > 0:
        lines.append(f"**Total at-risk value: {_fmt(r['total_at_risk_value'])}**\n")
    if not r['items']:
        lines.append("✅ No at-risk deals identified."); return '\n'.join(lines)
    lines += ['| Deal | Value | Stage | Risk Reason |', '|------|-------|-------|-------------|']
    for item in r['items']:
        vs = _fmt(float(item['value'])) if item['value'] and not math.isnan(float(item['value'] or 0)) else 'N/A'
        lines.append(f"| {item['name']} | {vs} | {item['stage']} | {'; '.join(item['reasons'])} |")
    return '\n'.join(lines)


def render_forecast(r):
    cov   = (r['weighted_forecast'] / r['total_pipeline'] * 100) if r['total_pipeline'] > 0 else 0
    lines = ['## \U0001f52e Revenue Forecast (Probability-Weighted)\n']
    lines += ['| Metric | Value |', '|--------|-------|']
    lines.append(f"| Total pipeline | {_fmt(r['total_pipeline'])} |")
    lines.append(f"| **Weighted forecast** | **{_fmt(r['weighted_forecast'])}** |")
    lines.append(f"| Coverage ratio | {cov:.1f}% |")
    if r['by_stage']:
        lines += ['\n### By Stage', '| Stage | Count | Raw Value | Prob | Weighted |', '|-------|-------|-----------|------|---------|']
        for stage, info in sorted(r['by_stage'].items(), key=lambda x: x[1]['weighted_value'], reverse=True):
            lines.append(f"| {stage} | {info['count']} | {_fmt(info['raw_value'])} | {info['probability']*100:.0f}% | {_fmt(info['weighted_value'])} |")
    lines.append(f"\n> \U0001f4dd _{r['note']}_")
    return '\n'.join(lines)


def render_general(r):
    lines = ['## \U0001f4cb Business Snapshot\n']
    lines.append(f"**Deals:** {r['deals_count']} | **Pipeline Value:** {_fmt(r['deals_value'])}")
    lines.append(f"\n**Work Orders:** {r['wo_count']} | **WO Value:** {_fmt(r['wo_value'])}")
    lines += ['\n_Try asking:_', "- _'How's our pipeline looking?'_",
              "- _'Show me at-risk deals'_", "- _'Revenue forecast'_",
              "- _'Energy sector performance'_", "- _'Work order completion rate'_"]
    return '\n'.join(lines)


RENDER_DISPATCH = {
    'pipeline_overview': render_pipeline_overview,
    'revenue':           render_revenue,
    'sector_analysis':   render_sector_analysis,
    'work_orders':       render_work_orders,
    'at_risk':           render_at_risk,
    'forecast':          render_forecast,
    'general':           render_general,
}


print('✅ Response renderer ready')

✅ Response renderer ready

In [20]:
# ── Skylark BI Agent Class ───────────────────────────────────────────────

class SkylarBIAgent:
    """
    Pure NLP Business Intelligence Agent for Skylark Drones Monday.com data.

    Pipeline: query -> tokenise -> intent classify -> entity extract
              -> query execute -> render response -> display markdown
    """

    HELP_TEXT = """
## \U0001f681 Skylark BI Agent \u2014 Help

**Pipeline & Deals**
- *How's our sales pipeline looking overall?*
- *Show me deals by stage*
- *Energy sector deals this quarter*

**Revenue**
- *What's our total revenue?*
- *Revenue breakdown by sector*
- *Largest deals in negotiation stage*

**Work Orders**
- *Work order completion rate*
- *Any blocked or overdue projects?*

**Risk & Forecast**
- *Show me at-risk deals*
- *Revenue forecast*

**Sector & Cross-Board**
- *Which sectors are performing best?*
"""

    def __init__(self):
        self.history = []
        self.context = {}

    def ask(self, question: str) -> str:
        """Process a natural language BI question and display formatted response."""
        question = question.strip()
        if not question: return

        if re.search(r'\b(help|what can you|capabilities|commands)\b', question.lower()):
            display(Markdown(self.HELP_TEXT)); return

        # Step 1: Classify intent
        intent, scores, tokens = classify_intent(question)

        # Step 2: Extract entities
        entities = extract_entities(question)

        # Step 3: Follow-up context resolution
        if intent == 'general' and self.context.get('last_intent'):
            if any(t in tokens for t in ['breakdown','detail','more','sector','stage','drill']):
                intent = self.context['last_intent']
                if not entities['sector']: entities['sector'] = self.context.get('last_sector')
                if not entities['time']:   entities['time']   = self.context.get('last_time')

        # Step 4: Execute query
        if intent == 'leadership_update':
            empty = {'time': {}, 'sector': None, 'stage': None, 'top_n': None}
            result = {
                'type': 'leadership_update',
                'pipeline': query_pipeline_overview(empty),
                'revenue':  query_revenue(empty),
                'wo':       query_work_orders(empty),
                'at_risk':  query_at_risk(empty),
                'forecast': query_forecast(empty),
            }
            md = self._render_leadership(result)
            display(Markdown(md))
        elif intent in QUERY_DISPATCH:
            result  = QUERY_DISPATCH[intent](entities)
            renderer = RENDER_DISPATCH.get(result['type'], render_general)
            md = renderer(result)
            display(Markdown(md))
        else:
            result = query_general(entities, tokens)
            md = render_general(result)
            display(Markdown(md))
            intent = 'general'

        # Step 5: Update context
        self.context = {'last_intent': intent, 'last_sector': entities['sector'], 'last_time': entities['time']}
        self.history.append({'q': question, 'intent': intent, 'entities': entities})
        return md

    def _render_leadership(self, r):
        p = r['pipeline']; w = r['wo']; a = r['at_risk']; f = r['forecast']
        won_val = sum(p['stage_breakdown'].get(s,{}).get('value',0) for s in p['stage_breakdown'] if 'won' in s.lower())
        lines = [f"## \U0001f681 Skylark Drones \u2014 Leadership Snapshot\n**{date.today().strftime('%d %B %Y')}**\n"]
        lines += ['### \U0001f3af Headline KPIs\n| KPI | Value |\n|-----|-------|']
        lines.append(f"| Pipeline Value | **{_fmt(p['total_value'])}** |")
        lines.append(f"| Active Deals | **{p['total_deals']}** |")
        lines.append(f"| Win Rate | **{p['win_rate']:.1f}%** |")
        lines.append(f"| Won Value | **{_fmt(won_val)}** |")
        lines.append(f"| Weighted Forecast | **{_fmt(f['weighted_forecast'])}** |")
        lines.append(f"| WO Completion Rate | **{w['completion_rate']:.1f}%** |")
        lines.append(f"| Overdue WOs | **{w['overdue']}** |")
        lines.append('\n### \U0001f4c8 Pipeline Health')
        for stage, info in sorted(p['stage_breakdown'].items(), key=lambda x: x[1]['value'], reverse=True)[:5]:
            lines.append(f"- **{stage}**: {info['count']} deals | {_fmt(info['value'])}")
        lines.append('\n### ⚙️ Operations')
        lines.append(f"- ✅ Completed: {w['completed']}  |  \U0001f504 In Progress: {w['in_progress']}  |  \U0001f6ab Blocked: {w['blocked']}")
        lines.append('\n### ⚠️ Risks')
        if a['count'] > 0:
            lines.append(f"- **{a['count']} at-risk deals** totalling {_fmt(a['total_at_risk_value'])}")
            for item in a['items'][:3]:
                vs = _fmt(float(item['value'])) if item['value'] else 'N/A'
                lines.append(f"  - {item['name']} ({vs}): {', '.join(item['reasons'])}")
        else:
            lines.append('- ✅ No critical risks identified')
        if w['blocked'] > 0:  lines.append(f"- \U0001f6ab {w['blocked']} blocked work orders")
        if w['overdue']  > 0: lines.append(f"- ⏰ {w['overdue']} overdue work orders")
        return '\n'.join(lines)

    def reset(self):
        self.history = []; self.context = {}; print('✅ Conversation reset')

    def debug(self, question: str):
        """Show NLP pipeline internals."""
        intent, scores, tokens = classify_intent(question)
        entities = extract_entities(question)
        print(f'Tokens  : {tokens}')
        print(f'Intent  : {intent}')
        print(f'Top scores: {dict(sorted(scores.items(), key=lambda x: x[1], reverse=True)[:4])}')
        print(f'Entities: {entities}')


# Instantiate
agent = SkylarBIAgent()
print('✅ NLP BI Agent ready — call agent.ask("your question")')
print('   Type agent.ask("help") for example queries.')

✅ NLP BI Agent ready — call agent.ask("your question")
   Type agent.ask("help") for example queries.

### 6.1 Example Queries

Run each cell to see how the agent responds. Edit the question string to ask your own.

In [21]:
# ── Pipeline overview ──
agent.ask("How's our sales pipeline looking overall? Give me stage breakdown and total value.")

## 📊 Pipeline Overview (all time)

**Total Deals:** 3  |  **Pipeline Value:** ₹0  |  **Win Rate:** 0.0%


### 💡 Insights
- ⚠️ Win rate at **0.0%** — review qualification criteria

> 📝 _No value col_

'## 📊 Pipeline Overview (all time)\n\n**Total Deals:** 3  |  **Pipeline Value:** ₹0  |  **Win Rate:** 0.0%\n\n\n### 💡 Insights\n- ⚠️ Win rate at **0.0%** — review qualification criteria\n\n> 📝 _No value col_'

In [22]:
# ── Sector performance ──
agent.ask("Which sectors are generating the most revenue across both deals and work orders?")

## ⚙️ Work Orders Report (all time)

| Metric | Value |
|--------|-------|
| Total Orders | **182** |
| Completed | ✅ 1 (0.5%) |
| In Progress | 🔄 0 |
| Blocked | 🚫 0 |
| Overdue | ⏰ 4 |

### 💡 Insights
- ⚠️ Low completion rate (**1%**) — consider resource reallocation
- ⏰ **4 overdue orders** — review timelines

### Status Breakdown
| Status | Count |
|--------|-------|
| Working On It | 1 |
| Completed | 1 |

'## ⚙️ Work Orders Report (all time)\n\n| Metric | Value |\n|--------|-------|\n| Total Orders | **182** |\n| Completed | ✅ 1 (0.5%) |\n| In Progress | 🔄 0 |\n| Blocked | 🚫 0 |\n| Overdue | ⏰ 4 |\n\n### 💡 Insights\n- ⚠️ Low completion rate (**1%**) — consider resource reallocation\n- ⏰ **4 overdue orders** — review timelines\n\n### Status Breakdown\n| Status | Count |\n|--------|-------|\n| Working On It | 1 |\n| Completed | 1 |'

In [ ]:
# ── At-risk deals ──
agent.ask("Show me deals that look at risk of stalling — overdue close dates or stuck too long.")

In [24]:
# ── Work order operations ──
agent.ask("What's the current work order completion rate? Any overdue or blocked projects?")

## ⚙️ Work Orders Report (all time)

| Metric | Value |
|--------|-------|
| Total Orders | **182** |
| Completed | ✅ 1 (0.5%) |
| In Progress | 🔄 0 |
| Blocked | 🚫 0 |
| Overdue | ⏰ 4 |

### 💡 Insights
- ⚠️ Low completion rate (**1%**) — consider resource reallocation
- ⏰ **4 overdue orders** — review timelines

### Status Breakdown
| Status | Count |
|--------|-------|
| Working On It | 1 |
| Completed | 1 |

'## ⚙️ Work Orders Report (all time)\n\n| Metric | Value |\n|--------|-------|\n| Total Orders | **182** |\n| Completed | ✅ 1 (0.5%) |\n| In Progress | 🔄 0 |\n| Blocked | 🚫 0 |\n| Overdue | ⏰ 4 |\n\n### 💡 Insights\n- ⚠️ Low completion rate (**1%**) — consider resource reallocation\n- ⏰ **4 overdue orders** — review timelines\n\n### Status Breakdown\n| Status | Count |\n|--------|-------|\n| Working On It | 1 |\n| Completed | 1 |'

In [23]:
# ── Revenue forecast ──
agent.ask("Give me a revenue forecast based on current pipeline.")

## 🔮 Revenue Forecast (Probability-Weighted)

| Metric | Value |
|--------|-------|
| Total pipeline | ₹0 |
| **Weighted forecast** | **₹0** |
| Coverage ratio | 0.0% |

> 📝 _Probability weights: Lead 10%, Prospect 20%, Qualified 35%, Proposal 50%, Negotiation 75%, Won 100%_

'## 🔮 Revenue Forecast (Probability-Weighted)\n\n| Metric | Value |\n|--------|-------|\n| Total pipeline | ₹0 |\n| **Weighted forecast** | **₹0** |\n| Coverage ratio | 0.0% |\n\n> 📝 _Probability weights: Lead 10%, Prospect 20%, Qualified 35%, Proposal 50%, Negotiation 75%, Won 100%_'

In [ ]:
# ── Custom question ──
agent.ask("What's our total contracted value across all active work orders this quarter?")

In [ ]:
# ── Debug mode: inspect the NLP pipeline ──────────────────────────────
agent.debug("Show me energy sector pipeline deals for Q2")

## 7. Leadership Update Generator

Generates a structured weekly update suitable for board meetings, investor calls, or leadership standups.
Built entirely from **live computed metrics**

In [25]:
# ── Leadership Update Builder ─────────────────────────────────────────────

def generate_leadership_update(save_to_file: bool = True) -> str:
    """Compute all KPIs and assemble a structured executive report."""
    today = date.today().strftime('%d %B %Y')
    empty = {'time': {}, 'sector': None, 'stage': None, 'top_n': None}

    pipeline = query_pipeline_overview(empty)
    revenue  = query_revenue(empty)
    wo_data  = query_work_orders(empty)
    at_risk  = query_at_risk(empty)
    forecast = query_forecast(empty)

    won_value = sum(pipeline['stage_breakdown'].get(s,{}).get('value',0)
                    for s in pipeline['stage_breakdown'] if 'won' in s.lower())

    kpi_rows = [
        f"| Total Pipeline Value | **{_fmt(pipeline['total_value'])}** |",
        f"| Active Deals | **{pipeline['total_deals']}** |",
        f"| Win Rate | **{pipeline['win_rate']:.1f}%** |",
        f"| Won Value | **{_fmt(won_value)}** |",
        f"| Weighted Forecast | **{_fmt(forecast['weighted_forecast'])}** |",
        f"| Total Work Orders | **{wo_data['total']}** |",
        f"| WO Completion Rate | **{wo_data['completion_rate']:.1f}%** |",
        f"| Blocked WOs | **{wo_data['blocked']}** |",
        f"| Overdue WOs | **{wo_data['overdue']}** |",
    ]

    pipeline_lines = []
    for stage, info in sorted(pipeline['stage_breakdown'].items(), key=lambda x: x[1]['value'], reverse=True)[:6]:
        pipeline_lines.append(f"  - **{stage}**: {info['count']} deals | {_fmt(info['value'])}")

    ops_lines = [
        f"  - ✅ Completed: {wo_data['completed']} orders",
        f"  - \U0001f504 In Progress: {wo_data['in_progress']} orders",
        f"  - \U0001f6ab Blocked: {wo_data['blocked']} orders",
        f"  - ⏰ Overdue: {wo_data['overdue']} orders",
    ]
    if wo_data['total_value'] > 0:
        ops_lines.append(f"  - \U0001f4b0 Total WO Value: {_fmt(wo_data['total_value'])}")

    risk_lines = []
    if at_risk['count'] > 0:
        risk_lines.append(f"  - ⚠️ **{at_risk['count']} at-risk deals** totalling {_fmt(at_risk['total_at_risk_value'])}")
        for item in at_risk['items'][:3]:
            vs = _fmt(float(item['value'])) if item['value'] else 'N/A'
            risk_lines.append(f"    - {item['name']} ({vs}): {', '.join(item['reasons'])}")
    if wo_data['blocked'] > 0:
        risk_lines.append(f"  - \U0001f6ab **{wo_data['blocked']} blocked work orders** — immediate attention required")
    if wo_data['overdue'] > 0:
        risk_lines.append(f"  - ⏰ **{wo_data['overdue']} overdue work orders** — timeline review needed")
    if not risk_lines: risk_lines = ['  - ✅ No critical risks identified this period']

    actions = []
    if at_risk['count'] > 0:
        actions.append(f"1. **Review {at_risk['count']} at-risk deals** — assign owner and define next action within 48h")
    if wo_data['blocked'] > 0:
        actions.append(f"2. **Unblock {wo_data['blocked']} work orders** — identify bottleneck and escalate if needed")
    if pipeline['win_rate'] < 25:
        actions.append("3. **Review deal qualification** — win rate below 25%, sharpen ICP criteria")
    elif forecast['weighted_forecast'] < pipeline['total_value'] * 0.4:
        actions.append("3. **Accelerate deals in proposal/negotiation** — weighted forecast coverage below 40%")
    if not actions:
        actions = ['1. Continue monitoring pipeline velocity',
                   '2. Ensure all deals have updated close dates',
                   '3. Schedule sector-specific pipeline reviews']

    data_notes = []
    if val_col and int(deals[val_col].isna().sum()) > 0:
        data_notes.append(f"  - {int(deals[val_col].isna().sum())} deals missing value data")
    if wo_val_col and int(wo[wo_val_col].isna().sum()) > 0:
        data_notes.append(f"  - {int(wo[wo_val_col].isna().sum())} work orders missing value data")
    if not data_notes: data_notes = ['  - Data quality looks good']

    NL = '\n'
    update = f"""# \U0001f681 Skylark Drones \u2014 Weekly Business Update
**Date:** {today}  |  **Generated by:** Skylark NLP BI Agent

---

## \U0001f3af Headline KPIs

| KPI | Value |
|-----|-------|
{NL.join(kpi_rows)}

---

## \U0001f4c8 Pipeline Health

**Total pipeline: {_fmt(pipeline['total_value'])}** across **{pipeline['total_deals']} deals** with a **{pipeline['win_rate']:.1f}% win rate**.

Stage breakdown (top 6 by value):
{NL.join(pipeline_lines)}

**Probability-weighted forecast: {_fmt(forecast['weighted_forecast'])}**

---

## ⚙️ Operational Highlights

{NL.join(ops_lines)}

---

## ⚠️ Risks & Attention Items

{NL.join(risk_lines)}

---

## ✅ Recommended Actions

{NL.join(actions)}

---

## \U0001f4cb Data Notes

{NL.join(data_notes)}

---
_Report generated automatically from Monday.com live data using Skylark NLP BI Agent._
"""

    display(Markdown(update))

    if save_to_file:
        filename = f'leadership_update_{date.today().isoformat()}.md'
        with open(filename, 'w') as f:
            f.write(update)
        print(f'\n✅ Saved to {filename}')

    return update


# Run the leadership update
leadership_report = generate_leadership_update(save_to_file=True)

# 🚁 Skylark Drones — Weekly Business Update
**Date:** 10 March 2026  |  **Generated by:** Skylark NLP BI Agent

---

## 🎯 Headline KPIs

| KPI | Value |
|-----|-------|
| Total Pipeline Value | **₹0** |
| Active Deals | **3** |
| Win Rate | **0.0%** |
| Won Value | **₹0** |
| Weighted Forecast | **₹0** |
| Total Work Orders | **182** |
| WO Completion Rate | **0.5%** |
| Blocked WOs | **0** |
| Overdue WOs | **4** |

---

## 📈 Pipeline Health

**Total pipeline: ₹0** across **3 deals** with a **0.0% win rate**.

Stage breakdown (top 6 by value):


**Probability-weighted forecast: ₹0**

---

## ⚙️ Operational Highlights

  - ✅ Completed: 1 orders
  - 🔄 In Progress: 0 orders
  - 🚫 Blocked: 0 orders
  - ⏰ Overdue: 4 orders

---

## ⚠️ Risks & Attention Items

  - ⏰ **4 overdue work orders** — timeline review needed

---

## ✅ Recommended Actions

3. **Review deal qualification** — win rate below 25%, sharpen ICP criteria

---

## 📋 Data Notes

  - 182 work orders missing value data

---
_Report generated automatically from Monday.com live data using Skylark NLP BI Agent._

UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f681' in position 2: character maps to <undefined>

In [26]:
agent.ask("Give me the weekly leadership update")

## 🚁 Skylark Drones — Leadership Snapshot
**10 March 2026**

### 🎯 Headline KPIs
| KPI | Value |
|-----|-------|
| Pipeline Value | **₹0** |
| Active Deals | **3** |
| Win Rate | **0.0%** |
| Won Value | **₹0** |
| Weighted Forecast | **₹0** |
| WO Completion Rate | **0.5%** |
| Overdue WOs | **4** |

### 📈 Pipeline Health

### ⚙️ Operations
- ✅ Completed: 1  |  🔄 In Progress: 0  |  🚫 Blocked: 0

### ⚠️ Risks
- ✅ No critical risks identified
- ⏰ 4 overdue work orders

'## 🚁 Skylark Drones — Leadership Snapshot\n**10 March 2026**\n\n### 🎯 Headline KPIs\n| KPI | Value |\n|-----|-------|\n| Pipeline Value | **₹0** |\n| Active Deals | **3** |\n| Win Rate | **0.0%** |\n| Won Value | **₹0** |\n| Weighted Forecast | **₹0** |\n| WO Completion Rate | **0.5%** |\n| Overdue WOs | **4** |\n\n### 📈 Pipeline Health\n\n### ⚙️ Operations\n- ✅ Completed: 1  |  🔄 In Progress: 0  |  🚫 Blocked: 0\n\n### ⚠️ Risks\n- ✅ No critical risks identified\n- ⏰ 4 overdue work orders'

In [ ]:
# Alternatively trigger via agent:
# agent.ask("Give me the weekly leadership update")

## 8. Utilities

Helper cells for refreshing data, inspecting columns, and resetting conversation state.

In [28]:
# ── Refresh data from Monday.com ───────────────────────────────────────────
def refresh_data():
    global deals, wo, val_col, status_col, sector_col
    global wo_val_col, wo_status_col, wo_sector_col
    print('Refreshing from Monday.com...')
    _, _, deals_items = get_board_items(deals_id)
    _, _, wo_items    = get_board_items(wo_id)
    deals = auto_clean(items_to_dataframe(deals_items), 'deals')
    wo    = auto_clean(items_to_dataframe(wo_items), 'workorders')
    val_col       = find_col(deals, ['value','amount','revenue','arr','deal size'])
    status_col    = find_col(deals, ['stage','status','phase'])
    sector_col    = find_col(deals, ['sector','industry','vertical','segment'])
    wo_val_col    = find_col(wo, ['value','amount','budget','revenue','cost','price'])
    wo_status_col = find_col(wo, ['status','stage','state'])
    wo_sector_col = find_col(wo, ['sector','industry','client','category','type'])
    print(f'✅ Refreshed: {len(deals)} deals, {len(wo)} work orders')

# Uncomment to run:
# refresh_data()

In [29]:
# ── Inspect column names ──────────────────────────────────────────────────
print('DEALS columns:')
for c in deals.columns: print(f'  {c}')
print('\nWORK ORDERS columns:')
for c in wo.columns: print(f'  {c}')

DEALS columns:
  _id
  _name
  Owner
  Status
  Date

WORK ORDERS columns:
  _id
  _name
  Person
  Status
  Date
  Value
  Start Date
  End Date

In [30]:
# ── Reset agent conversation ─────────────────────────────────────────────
# agent.reset()

# View conversation history
print('Query history:')
for i, h in enumerate(agent.history, 1):
    print(f'  {i}. [{h["intent"]}] {h["q"]}')

Query history:
  1. [pipeline_overview] How's our sales pipeline looking overall? Give me stage breakdown and total value.
  2. [work_orders] Which sectors are generating the most revenue across both deals and work orders?
  3. [forecast] Give me a revenue forecast based on current pipeline.
  4. [work_orders] What's the current work order completion rate? Any overdue or blocked projects?
  5. [leadership_update] Give me the weekly leadership update